apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-pvc-1
spec: 
  containers: 
    - name: my-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: pvc-volume
  volumes:
    - name: pvc-volume
      persistentVolumeClaim: 
        claimName: pvc-local
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: pvc-local-1
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-local-1
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data