apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-pvc
spec: 
  containers: 
    - name: my-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: pvc-volume
  volumes:
    - name: pvc-volume
      persistentVolumeClaim: 
        claimName: pvc-local
        