apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spac:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  startegy: {}
  template:
    metadata:
      creationTimestamo: null
      labels:   
        app: nginx
    spec: 
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}