apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app: nginx
    nameofcreator: aayush 
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}